### ISSUE TITLE
Would a practical session about SignalR + Rx be interesting?

### ISSUE THREAD

**Issue by wasphub** [Web-European-Conference/c4p#13]
I was thinking I could talk about that stuff, basing my talk on the [RElmah](https://github.com/wasphub/RElmah) project I'm (painfully slowly) building. A practical session showing some architecture and some solutions to specific problems in that area. I'm just opening an issue and not sending a PR yet because I'm not yet sure I could do it, but if you think it could be a good topic I can try to plan my stuff and see if I can make it.

**Comment by simonech** [comment]
The idea is interesting. If you think you could do it, please submit a
proposal. Then in June we'll evaluate all proposals and will decide which
one to put into the agenda of the conf.


On Tue, Mar 31, 2015 at 3:17 PM, Roberto Vespa <notifications@github.com>
wrote:

> I was thinking I could talk about that stuff, basing my talk on the RElmah
> <https://github.com/wasphub/RElmah> project I'm (painfully slowly)
> building. A practical session showing some architecture and some solutions
> to specific problems in that area. I'm just opening an issue and not
> sending a PR yet because I'm not yet sure I could do it, but if you think
> it could be a good topic I can try to plan my stuff and see if I can make
> it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Web-European-Conference/c4p/issues/13>.
>



-- 
Simone Chiaretta
Microsoft MVP ASP.NET - ASPInsider
Blog: http://codeclimber.net.nz
RSS: http://feeds2.feedburner.com/codeclimber
twitter: @simonech

**Comment by wasphub** [comment]
Ok, thanks, I'll think about it and get back with a proposal in case I think I can handle it.
